apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - name: port-80
    port: 80
    targetPort: 80
    protocol: TCP
  - name: port-443
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 80
        volumeMounts:
          - name: conf
            mountPath: /etc/nginx
          - name: static
            mountPath: /data/static
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim
        - name: conf
          hostPath:
            path: /run/desktop/mnt/host/d/code/stone/deployment/conf/nginx
        - name: static
          hostPath:
            path: /run/desktop/mnt/host/d/stone/data