#apiVersion: v1
#kind: Service
#metadata:
#  name: celery-service
#spec:
#  selector:
#    app: celery

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  selector:
    matchLabels:
      app: celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - image: celery
        name: celery
#        ports:
#        - containerPort: 5672
        resources:
          limits:
            cpu: 100m